#你的conda.sh路径{conda_install_path}/etc/profile.d/conda.sh
conda_install_path: /home/yxiaobo/miniconda3

#参考基因组
genome:
  indexdir: "/home/public_software_annotation/genomeanno/mousehisat2Index/GRCm38"          ##hisat2 参考基因组，可自行修改对应路径
  gfffile: "/home/public_software_annotation/genomeanno/gencode.vM25.mRNA.annotation.gtf"  ##stringtie 参考注释文件路径，可自行修改对应路径


#线程数
threads:
  trim_galore: 4  ##质控，可根据实际情况修改数量
  fastp: 5        ##进一步质控
  hisat2: 4       ##比对
  samtools: 4     ##转换排序
  stringtie: 5    ##转录本组装


#  去重参数
picard:
  java_mem: "-Xmx15g"  ## JVM 最大堆内存设置为15GB,可根据实际情况修改
  remove_dups: "true"  ## 是否删除重复 reads，"true"/"false",推荐为"true"，可根据实际情况修改
  picarddir: "/home/public_software_annotation/software/picard-2.18.2"  ## Picard 路径，可根据实际情况修改


#生成列表文件
names:
  mmESC_24h_DOX_1: SRR4032346  ##对应的组别名称(如mmESC_24h_DOX_1)和样本SRR号（SRR4032346 ）可根据实际需求对应修改和增减
  mmESC_24h_DOX_2: SRR4032347
  mmESC_no_DOX_1: SRR4032348
  mmESC_no_DOX_2: SRR4032349


#分组
group:
  sample_IDs:     
    mmESC_24h_DOX_1: P   ##对应的组别名称和上面names的要一致，且P代表实验组，T代表对照组
    mmESC_24h_DOX_2: P
    mmESC_no_DOX_1: T  
    mmESC_no_DOX_2: T

